// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RTrid1mEBwz01QbM5LEGhwNRS73duhc',
    appId: '1:504714835540:web:388504f2cfb1a1eaacdfc1',
    messagingSenderId: '504714835540',
    projectId: 'mach-mit-bd36f',
    authDomain: 'mach-mit-bd36f.firebaseapp.com',
    storageBucket: 'mach-mit-bd36f.firebasestorage.app',
    measurementId: 'G-9JMZB9X1ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9SPXsOHvVAapfMeXndg3xTK-yCcBz-0',
    appId: '1:504714835540:android:993bede7fe194e51acdfc1',
    messagingSenderId: '504714835540',
    projectId: 'mach-mit-bd36f',
    storageBucket: 'mach-mit-bd36f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL-S6o4HQ_dz2kB8_f0esJIGVSgIAytJY',
    appId: '1:504714835540:ios:102ec2ba832e2fb8acdfc1',
    messagingSenderId: '504714835540',
    projectId: 'mach-mit-bd36f',
    storageBucket: 'mach-mit-bd36f.firebasestorage.app',
    iosBundleId: 'com.example.machMit',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL-S6o4HQ_dz2kB8_f0esJIGVSgIAytJY',
    appId: '1:504714835540:ios:102ec2ba832e2fb8acdfc1',
    messagingSenderId: '504714835540',
    projectId: 'mach-mit-bd36f',
    storageBucket: 'mach-mit-bd36f.firebasestorage.app',
    iosBundleId: 'com.example.machMit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8RTrid1mEBwz01QbM5LEGhwNRS73duhc',
    appId: '1:504714835540:web:c3453d3f0897e96dacdfc1',
    messagingSenderId: '504714835540',
    projectId: 'mach-mit-bd36f',
    authDomain: 'mach-mit-bd36f.firebaseapp.com',
    storageBucket: 'mach-mit-bd36f.firebasestorage.app',
    measurementId: 'G-LQ6M27WBWB',
  );
}
